language: cpp
script: cmake

sudo: required
dist: trusty

os: linux
compiler: clang
env: CLANG_VERSION=3.9 LIBCXX=On BUILD_TYPE=Debug
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    packages: ['clang-3.9', 'libstdc++6', 'valgrind']

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ./install-cmake.sh
  - if [ -n "$CLANG_VERSION"  ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [ "$LIBCXX" == "On" ]; then CXX_FLAGS="${CXX_FLAGS} -stdlib=libc++ -I/usr/include/c++/v1/"; fi
  - if [ "$LIBCXX" == "On" ]; then CXX_LINKER_FLAGS="${CXX_FLAGS} -L/usr/lib/ -lc++"; fi
  - which $CXX
  - which $CC
  - $CXX --version

script:
  - mkdir -p build
  - cd build
  - ../cmake/bin/cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make VERBOSE=1

notifications:
  email: false
