language: cpp
script: cmake

sudo: required
dist: trusty

env: CLANG_VERSION=3.9 BUILD_TYPE=Debug
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - util-linux
      - clang-3.9
      - valgrind

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ./install-cmake.sh
  - if [ -n "$CLANG_VERSION"  ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version

script:
  - mkdir -p build
  - cd build
  - ../cmake/bin/cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make VERBOSE=1

notifications:
  email: false
